services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'daryz/translatet-app:latest'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/translations
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: adminpassword
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=translations
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: