spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/translations
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver